const llmService = require('../services/llmService');
const searchAgent = require('./searchAgent');
const bookingAgent = require('./bookingAgent');
const faqAgent = require('./faqAgent');
const promptService = require('../services/promptService');

const handle = async (messages) => {
    console.log("-> Router Agent Analysis...");

    const lastUserMessage = messages[messages.length - 1].content;

    // Classification Step
    // We need to pass the recent conversation history so the router understands context (e.g., answering a question)
    const recentHistory = messages
        .slice(-5) // Look at last 5 messages
        .map(m => `${m.role.toUpperCase()}: ${m.content}`)
        .join('\n');

    const classificationPrompt = [
        { role: "system", content: promptService.render('router', { history: recentHistory }) },
        { role: "user", content: lastUserMessage }
    ];

    // Request JSON mode for robustness
    const response = await llmService.getCompletion(classificationPrompt, 'gpt-4o', true);

    let cleanIntent = 'GENERAL';
    let generalResponse = "I'm not sure how to help with that.";

    try {
        const parsed = JSON.parse(response);
        cleanIntent = parsed.intent ? parsed.intent.toUpperCase() : 'GENERAL';
        generalResponse = parsed.response;
        console.log(`-> Router Logic: ${parsed.reasoning}`);
    } catch (e) {
        console.error("Router JSON Parse Error:", e);
        // Fallback
        cleanIntent = 'GENERAL';
        generalResponse = response; // Best effort
    }

    console.log(`-> Intent Detected: ${cleanIntent}`);

    // Handoff Logic
    switch (cleanIntent) {
        case 'SEARCH':
            return await searchAgent.handle(messages);
        case 'BOOKING':
            return await bookingAgent.handle(messages);
        case 'FAQ':
            return await faqAgent.handle(messages);
        case 'GENERAL':
        default:
            // Return the response generated by the router prompt directly!
            // No distinct general prompt needed anymore.
            return generalResponse || "Hello! How can I help you with your flights today?";
    }
};

module.exports = { handle };
